### PR TITLE
Fix/speedup AES

### PR DESCRIPTION
**Pull request by ADiea**
Speedup aes functions.

### CODE REVIEW

**Comment by ADiea** [comment]
AES is used to encrypt data once session is established so it has impact throughout the ssl session (when CPU is back at 80Mhz)

**Comment by igrr** [comment]
Have you had a chance to measure how much speedup this change achieves, and how much extra space it needs in IRAM?

**Comment by igrr** [comment]
I think the best way to do this is to adjust the linker script to place aes.o object into IRAM.

**Comment by ADiea** [comment]
Fair enough.

**Pull request closed without merging**
